name: Quick Jenkins Trigger

on:
  workflow_dispatch:

jobs:
  trigger-jenkins:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Jenkins directly
        run: |
          set -euo pipefail
          JENKINS_URL="http://ip172-18-0-15-d2blqbk69qi000fihbh0-8080.direct.labs.play-with-docker.com"
          JENKINS_JOB_PATH="/job/pflex-test"
          JENKINS_USER="your-jenkins-username"
          JENKINS_API_TOKEN="117128a450700b3cbf102972c59f19b498"

          URL="$JENKINS_URL$JENKINS_JOB_PATH/build?cause=Triggered_from_GitHub"
          echo "POST $URL"
          code=$(curl -fsS -o /dev/null -w "%{http_code}" -I -X POST \
                 -u "$JENKINS_USER:$JENKINS_API_TOKEN" "$URL")
          echo "HTTP $code (expect 201)"; test "$code" = "201"
          echo "Triggered successfully."
